name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: devx-spring-petclinic
  JAVA_VERSION: "17" #Java version to use
  DISTRIBUTION: zulu # Java distribution
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # path to your web app project

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.actor != 'dependabot[bot]'}}
    permissions:
      id-token: write
      contents: none
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: look for downloaded artifact
        run: ls -lR

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create resource group
        run: az group create -l eastus -n td-petclinic-rg

      - name: Deploy resource from bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: td-petclinic-rg
          template: ./main.bicep
          failOnStdErr: false

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar"

      # Azure logout
      - name: logout
        run: |
          az logout
