name: Azure Load Testing

on:
  workflow_call:

env:
  LOAD_TEST_RESOURCE: "load-testing-ghaction"
  LOAD_TEST_RESOURCE_GROUP: "load-testing-ghaction-rg"

permissions:
  id-token: write
  contents: read

jobs:
  load-testing:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'petClinicTest.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}

      - name: logout
        run: |
          az logout
