name: Delete Resource Group

on:
  workflow_call:
  schedule:
    - cron: '0 0 * * *'
        
permissions:
  id-token: write
  contents: read
    
jobs:
  delete:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: dev
        
    steps:
      - uses: actions/checkout@v3
            
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete resource group
        run: |
          if [ $(az group exists -n td-petclinic-rg) = true ]; then
            az group delete -n td-petclinic-rg -y
          else
            echo "resource group does not exist"
          fi
              
      - name: Logout
        run: |
          az logout