name: Deploy to Azure

on:
  push:
    branches: [ "kevin-demo" ]

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    if: ${{ github.actor != 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Test az commands'
        run: |
          az account show
          az group list
          pwd 
      - name: Create resource group
        run: az group create -l eastus -n td-petclinic-rg
      
      