name: Generate Service Principal

env:
  SP_PWD: Wf98Q~UFKnCSkIKtOAUTkJp9OA1HCQm3L0vhScPH
  SP_TENANT: 83a73621-e992-49bb-9032-95101904d8d6
  SP_APP_ID: b3e718a0-213b-4c5f-9eb2-ce66635c5eb4

on:
  push:
    branches:
      - shane-generate-service-principal
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sp:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: "Azure CLI Login"
        run: az login --service-principal -u ${{ env.SP_APP_ID }} -p ${{ env.SP_PWD }} --tenant ${{ env.SP_TENANT }}

      - run: |
          subscriptionID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az ad sp create-for-rbac --name petclinicServicePrincipal2 \
                                   --role contributor \
                                   --scopes /subscriptions/$subscriptionID/resourceGroups/td-petclinic-rg
          
