name: Generate Service Principal

on:
  push:
    branches:
      - shane-generate-service-principal
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sp:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: "Azure CLI Login"
        run: az login --service-principal -u ${{ secrets.SP_APP_ID }} -p ${{ secrets.SP_PWD }} --tenant ${{ secrets.SP_TENANT }}

      - run: |
          subscriptionID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az ad sp create-for-rbac --name petclinicServicePrincipal2 \
                                   --role contributor \
                                   --scopes /subscriptions/$subscriptionID/resourceGroups/td-petclinic-rg
          
