name: On push to main

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: ./.github/workflows/maven-build.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
