name: On push to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-build-workflow:
    uses: ./.github/workflows/maven-build.yml
  call-codeql-workflow:
    uses: ./.github/workflows/codeql.yml
  call-package-workflow:
    uses: ./.github/workflows/packageWorkflow.yml

