name: On push to any branch

on:
  pull_request:
    branches: [ '**' ]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/maven-build.yml
  call-publish-test-results-workflow:
    uses: ./.github/workflows/test-results.yml
  call-codeql-workflow:
    uses: ./.github/workflows/codeql.yml
  call-veracode-workflow:
    uses: ./.github/workflows/veracode.yml
